import random
quotes = [
    "All their equipment and instruments are alive.",
    "A red flare silhouetted the jagged edge of a wing.",
    "I watched the storm, so beautiful yet terrific.",
    "Almost before we knew it, we had left the ground.",
    "A shining crescent far beneath the flying vessel.",
    "It was going to be a lonely trip back.",
    "Mist enveloped the ship three hours out from port.",
    "My two natures had memory in common.",
    "Silver mist suffused the deck of the ship.",
    "The face of the moon was in shadow.",
    "She stared through the window at the stars.",
    "The recorded voice scratched in the speaker.",
    "The sky was cloudless and of a deep dark blue.",
    "The spectacle before us was indeed sublime.",
    "Then came the night of the first falling star.",
    "Waves flung themselves at the blue evening.",
    "When you reach the end of your rope, tie a knot in it and hang on.",
    "Whoever is happy will make others happy too.",
    "Life is really simple, but we insist on making it complicated.",
    "May you live all the days of your life.",
    "Life itself is the most wonderful fairy tale.",
    "Do not let making a living prevent you from making a life.",
    "Life is ours to be spent, not to be saved.",
    "Life is a long lesson in humility.",
    "Love the life you live. Live the life you love.",
    "Life is either a daring adventure or nothing at all.",
    "Life is made of ever so many partings welded together.",
    "The secret of success is to do the common thing uncommonly well.",
    "I find that the harder I work, the more luck I seem to have.",
    "Choose a job you love, and you will never have to work a day in your life.",
    "Living to learn, learning to live.",
    "My software never has bugs. It just develops random features.",
    "If It ain't broke, then tweak It until It breaks!",
    "I'm not lazy. I'm in powersaving mode.",
    "I never lose. Either I win, or I learn.",
    "If you can dream it, you can do it.",
    "Don't let yesterday take up too much of today.",
    "If you want something, go get it, period.",
    "It always seems impossible until it's done.",
    "A smooth sea never made a skilled sailor.",
    "Don't wait for the perfect moment, take the moment and make it perfect.",
    "When you feel like quitting, think about why you started.",
    "To be a champ, you have to believe in yourself when nobody else will.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "If there are no ups and downs in your life, it means you are dead.",
    "Work until your idols become your rivals.",
    "To get something you never had, you have to do something you never did.",
    "You are never too old to set another goal or to dream a new dream."
]
def get_quote():
    return random.choice(quotes)

    